[build]
  publish = "build/"
  command = "npm run build"

[context.production]
  branch = "definitivo2.0"

[context.definitivo2]
  branch = "definitivo2.0"

# Configuración de caché - Forzar invalidación
[headers]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Robots-Tag = "noindex"

# Redirecciones agresivas para Railway
[[redirects]]
  from = "https://web-production-d1ba.up.railway.app/*"
  to = "https://sermalite-feedback-api.onrender.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://web-production-d1ba.up.railway.app/*"
  to = "https://sermalite-feedback-api.onrender.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://sermalite-feedback-api.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_API_URL = "https://sermalite-feedback-api.onrender.com/api"
  CI = "false"
  NODE_VERSION = "18.x"
