[build]
  command = "DISABLE_ESLINT_PLUGIN=true CI=false ESLINT_NO_DEV_ERRORS=true npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_API_URL = "https://sermalite-feedback-api.onrender.com/api"
  CI = "false"
  DISABLE_ESLINT_PLUGIN = "true"
  ESLINT_NO_DEV_ERRORS = "true"
