[build]
  publish = "build/"
  command = "npm run build"

[context.production]
  branch = "definitivo2.0"

[context.definitivo2]
  branch = "definitivo2.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_API_URL = "https://sermalite-feedback-api.onrender.com/api"
  CI = "false"
