[build]
  base = "client/"
  publish = "build/"
  command = "npm run build"

[context.production]
  branch = "Final"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_API_URL = "https://evaluacion-semestral-api.onrender.com"
  CI = "false"
