[build]
  base = "client/"
  publish = "build/"
  command = "CI=false DISABLE_ESLINT_PLUGIN=true npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_API_URL = "https://pdfeedback-api.onrender.com"
  CI = "false"
  DISABLE_ESLINT_PLUGIN = "true"
