services:
  # Backend API Service
  - type: web
    name: sermalite-feedback-api
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node scripts/createIndexes.js && node app.js
    healthCheckPath: /api/status
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        # Asegúrate de configurar esta variable en el dashboard de Render
        # Debe tener el formato: mongodb+srv://usuario:contraseña@cluster.mongodb.net/database
        sync: false
      - key: PDF_MONGODB_URI
        # Asegúrate de configurar esta variable en el dashboard de Render
        sync: false
      - key: JWT_SECRET
        # Asegúrate de configurar esta variable en el dashboard de Render
        # Debe ser una cadena segura y única para firmar los tokens JWT
        sync: false
      - key: GEMINI_API_KEY
        # Asegúrate de configurar esta variable en el dashboard de Render
        sync: false
      - key: LLMWHISPERER_API_KEY
        # Asegúrate de configurar esta variable en el dashboard de Render
        sync: false
      - key: LLMWHISPERER_BASE_URL_V2
        value: https://llmwhisperer-api.us-central.unstract.com/api/v2
      - key: PORT
        value: 10000
      # Variables para optimizaciones
      - key: CACHE_TTL
        value: 300
      - key: CACHE_CHECK_PERIOD
        value: 60
      - key: MAX_CONCURRENT_PROCESSING
        value: 8
      - key: PDF_PROCESSING_TIMEOUT
        value: 300
      # Configuración de Redis (opcional)
      - key: REDIS_HOST
        value: "localhost"
      - key: REDIS_PORT
        value: 6379
      - key: REDIS_TLS
        value: "false"

  # Frontend Static Site
  - type: web
    name: sermalite-feedback-client
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: sermalite-feedback-api
          type: web
          property: url
